image: docker.bestsens.de/bone/rust-build-image:master

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
    - build
    - deploy

.artifacts: &artifacts
    expire_in: 4 weeks
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
        - bone_shell
        - bone_shell_arm
        - bone_shell_x86_64.exe

## Build ##############################################################################################################
build:
    stage: build
    cache:
        paths:
            - .cargo
            - target
    artifacts:
        <<: *artifacts
    before_script:
        - mkdir -p ${CI_PROJECT_DIR}/.cargo
        - cp -r /usr/local/cargo/config ${CI_PROJECT_DIR}/.cargo/config
    script:
        - cargo build --release
        - cargo build --release --target=arm-unknown-linux-gnueabihf
        - cargo build --release --target=x86_64-pc-windows-gnu
        - cp target/release/bone_shell ./bone_shell
        - cp target/arm-unknown-linux-gnueabihf/release/bone_shell ./bone_shell_arm
        - cp target/x86_64-pc-windows-gnu/release/bone_shell.exe ./bone_shell_x86_64.exe

## Create persistent archives #########################################################################################
.deploy: &deploy
    stage: deploy
    when: on_success
    only:
        - tags
    variables:
        GIT_STRATEGY: none
    script:
        - echo '1'

deploy:
    <<: *deploy
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_arm"
        expire_in:
    dependencies:
        - build
