image: docker.bestsens.de/bone/rust-build-image:master

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
    - build
    - deploy

.artifacts: &artifacts
    expire_in: 4 weeks
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
        - bone_shell

## Build ##############################################################################################################
build:arm:
    stage: build
    cache:
      key: arm
      paths:
        - .cargo
        - target
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_arm"
    before_script:
        - mkdir -p ${CI_PROJECT_DIR}/.cargo
        - cp -r /usr/local/cargo/config ${CI_PROJECT_DIR}/.cargo/config
    script:
        - cargo build --release --target=arm-unknown-linux-gnueabihf
        - cp target/arm-unknown-linux-gnueabihf/release/bone_shell ./bone_shell

build:i686:
    stage: build
    cache:
      paths:
        - .cargo
        - target
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_i686"
    before_script:
        - mkdir -p ${CI_PROJECT_DIR}/.cargo
        - cp -r /usr/local/cargo/config ${CI_PROJECT_DIR}/.cargo/config
    script:
        - cargo build --release
        - cp target/release/bone_shell ./bone_shell

## Create persistent archives #########################################################################################
.deploy: &deploy
    stage: deploy
    when: on_success
    only:
        - tags
    variables:
        GIT_STRATEGY: none
    script:
        - echo '1'

deploy:arm:
    <<: *deploy
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_arm"
        expire_in:
    dependencies:
        - build:arm

deploy:i686:
    <<: *deploy
    artifacts:
        <<: *artifacts
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_i686"
        expire_in:
    dependencies:
        - build:i686
