image: docker.bestsens.de/bone/rust-build-image:master

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
    - build
    - release

.artifacts: &artifacts
    expire_in: 4 weeks
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
        - bone_shell
        - bone_shell_arm
        - bone_shell_x86_64.exe

## Build ##############################################################################################################
build:
    stage: build
    cache:
        paths:
            - .cargo
            - target
    artifacts:
        <<: *artifacts
    before_script:
        - mkdir -p ${CI_PROJECT_DIR}/.cargo
        - cp -r /usr/local/cargo/config ${CI_PROJECT_DIR}/.cargo/config
    script:
        - cargo build --release
        - cargo build --release --target=arm-unknown-linux-gnueabihf
        - cargo build --release --target=x86_64-pc-windows-gnu
        - cp target/release/bone_shell ./bone_shell
        - cp target/arm-unknown-linux-gnueabihf/release/bone_shell ./bone_shell_arm
        - cp target/x86_64-pc-windows-gnu/release/bone_shell.exe ./bone_shell_x86_64.exe

## Release ############################################################################################################
release_job:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    needs:
        - job: build
          artifacts: true
    only:
        - tags
    script:
        - echo 'releasing $_CI_COMMIT_TAG'
    release:
        name: '$CI_COMMIT_TAG'
        description: 'Automatically created'
        tag_name: '$CI_COMMIT_TAG'
        ref: '$CI_COMMIT_TAG'
        assets:
            links:
                - name: "Linux x86_64"
                  url: "https://gitlab.bestsens.de/bone/bone_shell/-/jobs/${GE_JOB_ID}/artifacts/file/bone_shell"
                - name: "Linux ARM"
                  url: "https://gitlab.bestsens.de/bone/bone_shell/-/jobs/${GE_JOB_ID}/artifacts/file/bone_shell_arm"
                - name: "Windows x86_64"
                  url: "https://gitlab.bestsens.de/bone/bone_shell/-/jobs/${GE_JOB_ID}/artifacts/file/bone_shell_x86_64.exe"
